<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Data-Cleaning" data-toc-modified-id="Data-Cleaning-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data Cleaning</a></span></li><li><span><a href="#Examining-Data-for-Potential-Issues" data-toc-modified-id="Examining-Data-for-Potential-Issues-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Examining Data for Potential Issues</a></span></li><li><span><a href="#Missing-Values" data-toc-modified-id="Missing-Values-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Missing Values</a></span><ul class="toc-item"><li><span><a href="#Show-the-number-of-null-values-only-of-the-columns-that-actually-have-null-values" data-toc-modified-id="Show-the-number-of-null-values-only-of-the-columns-that-actually-have-null-values-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Show the number of null values only of the columns that actually have null values</a></span></li><li><span><a href="#Remove-the-columns-that-have-more-than-10,000-null-values-in-them" data-toc-modified-id="Remove-the-columns-that-have-more-than-10,000-null-values-in-them-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Remove the columns that have more than 10,000 null values in them</a></span></li><li><span><a href="#Create-a-new-dataframe-that-shows-only-the-row-where-displ-is-null." data-toc-modified-id="Create-a-new-dataframe-that-shows-only-the-row-where-displ-is-null.-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Create a new dataframe that shows only the row where <code>displ</code> is null.</a></span></li><li><span><a href="#Fill-nan-values-with-the-most-appropriate-technique" data-toc-modified-id="Fill-nan-values-with-the-most-appropriate-technique-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Fill nan values with the most appropriate technique</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Bonus:</a></span></li></ul></li><li><span><a href="#Incorrect-Values" data-toc-modified-id="Incorrect-Values-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Incorrect Values</a></span><ul class="toc-item"><li><span><a href="#Check-similar-rows" data-toc-modified-id="Check-similar-rows-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Check similar rows</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Bonus:</a></span></li></ul></li><li><span><a href="#Low-Variance-Columns" data-toc-modified-id="Low-Variance-Columns-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Low Variance Columns</a></span><ul class="toc-item"><li><span><a href="#Use-the-the-drop-method-like-we-did-earlier-in-this-lesson-to-remove-the-non-informative-columns-from-our-data-frame." data-toc-modified-id="Use-the-the-drop-method-like-we-did-earlier-in-this-lesson-to-remove-the-non-informative-columns-from-our-data-frame.-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Use the the drop method like we did earlier in this lesson to remove the non informative columns from our data frame.</a></span></li></ul></li><li><span><a href="#Extreme-Values-and-Outliers" data-toc-modified-id="Extreme-Values-and-Outliers-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Extreme Values and Outliers</a></span></li><li><span><a href="#Data-Type-Correction" data-toc-modified-id="Data-Type-Correction-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Data Type Correction</a></span><ul class="toc-item"><li><span><a href="#Check-the-data-type-of-each-column" data-toc-modified-id="Check-the-data-type-of-each-column-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Check the data type of each column</a></span></li><li><span><a href="#Cleaning-years" data-toc-modified-id="Cleaning-years-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Cleaning years</a></span></li></ul></li><li><span><a href="#Cleaning-Text-and-Removing-Special-Characters" data-toc-modified-id="Cleaning-Text-and-Removing-Special-Characters-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Cleaning Text and Removing Special Characters</a></span></li><li><span><a href="#Finding-and-Removing-Duplicates" data-toc-modified-id="Finding-and-Removing-Duplicates-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Finding and Removing Duplicates</a></span><ul class="toc-item"><li><span><a href="#Drop-duplicate-rows-that-are-completely-equal" data-toc-modified-id="Drop-duplicate-rows-that-are-completely-equal-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Drop duplicate rows that are completely equal</a></span></li><li><span><a href="#Select-a-subset-of-columns,-remove-all-other-columns,-and-then-use-the-drop_duplicates-method-to-drop-any-duplicate-records-based-on-the-remaining-columns." data-toc-modified-id="Select-a-subset-of-columns,-remove-all-other-columns,-and-then-use-the-drop_duplicates-method-to-drop-any-duplicate-records-based-on-the-remaining-columns.-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Select a subset of columns, remove all other columns, and then use the drop_duplicates method to drop any duplicate records based on the remaining columns.</a></span></li></ul></li><li><span><a href="#Export-clean-dataset" data-toc-modified-id="Export-clean-dataset-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Export clean dataset</a></span></li></ul></div>

# Data Cleaning


Lab Goals

+ Examine data for potential issues.
+ Identify and fill in missing values.
+ Identify and correct incorrect values.
+ Remove low variance columns.
+ Identify potential outliers.
+ Correct incorrect data types.
+ Remove special characters and clean categorical variables.
+ Identify and remove duplicate records.

Introduction

When working with data sets, you will find that they often require a bit of cleaning. Whether Pandas originally read the data types incorrectly, records are duplicated, the data contains special characters or missing value, or there are slightly different references to the same entity, every data analyst must know how to clean the data they are working with before analyzing it. In this lesson, you will learn about some of the most common problems that make data messy and methods for correcting those problems and cleaning your data.

The data set we are going to be using for this lesson is a messy version of the vehicles data set we worked with in the previous lesson. Let's import this version of our data set so that we can then practice cleaning it up.

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Load data from vehicles_messy.csv

data_ori = pd.read_csv('../data/vehicles_messy.csv', low_memory=False)

# Examining Data for Potential Issues

One of the first things we want to do is examine the data and look for any **potential issues**. Some of the things we are interested in identifying in the data at this stage include:

- Missing values
- Special characters
- Incorrect values
- Extreme values or outliers
- Duplicate records
- Incorrect data types

The presence of these may cause problems when it's time to analyze the data, so we want to make sure we address them beforehand. We can start by visually inspecting the data using the `.head` method, which will show us the first 5 rows of data.

In [3]:
pd.set_option('display.max_columns', None)

data = data_ori.copy()

In [4]:
data.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

But how big actually is our dataframe??? Check it with `.shape` method

In [5]:
#your code
data.shape

(37843, 83)

Let's dive a little more in the content of our data set. Is there any method that shows us the **column names**, its **data types** and number of **non-null values**?

In [6]:
#your code
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 83 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   barrels08        37843 non-null  float64
 1   barrelsA08       37843 non-null  float64
 2   charge120        37843 non-null  float64
 3   charge240        37843 non-null  float64
 4   city08           37843 non-null  int64
 5   city08U          37843 non-null  float64
 6   cityA08          37843 non-null  int64
 7   cityA08U         37843 non-null  float64
 8   cityCD           37843 non-null  float64
 9   cityE            37843 non-null  float64
 10  cityUF           37843 non-null  float64
 11  co2              37843 non-null  int64
 12  co2A             37843 non-null  int64
 13  co2TailpipeAGpm  37843 non-null  float64
 14  co2TailpipeGpm   37843 non-null  float64
 15  comb08           37843 non-null  int64
 16  comb08U          37843 non-null  float64
 17  combA08          37843 non-null  int64
 18  combA08U         37843 non-null  float64
 19  combE            37843 non-null  float64
 20  combinedCD       37843 non-null  float64
 21  combinedUF       37843 non-null  float64
 22  cylinders        37720 non-null  float64
 23  displ            37723 non-null  float64
 24  drive            36654 non-null  object
 25  engId            37843 non-null  int64
 26  eng_dscr         22440 non-null  object
 27  feScore          37843 non-null  int64
 28  fuelCost08       37843 non-null  int64
 29  fuelCostA08      37843 non-null  int64
 30  fuelType         37843 non-null  object
 31  fuelType1        37843 non-null  object
 32  ghgScore         37843 non-null  int64
 33  ghgScoreA        37843 non-null  int64
 34  highway08        37843 non-null  int64
 35  highway08U       37843 non-null  float64
 36  highwayA08       37843 non-null  int64
 37  highwayA08U      37843 non-null  float64
 38  highwayCD        37843 non-null  float64
 39  highwayE         37843 non-null  float64
 40  highwayUF        37843 non-null  float64
 41  hlv              37843 non-null  int64
 42  hpv              37843 non-null  int64
 43  id               37843 non-null  int64
 44  lv2              37843 non-null  int64
 45  lv4              37843 non-null  int64
 46  make             37843 non-null  object
 47  model            37843 non-null  object
 48  mpgData          37843 non-null  object
 49  phevBlended      37843 non-null  bool
 50  pv2              37843 non-null  int64
 51  pv4              37843 non-null  int64
 52  range            37843 non-null  int64
 53  rangeCity        37843 non-null  float64
 54  rangeCityA       37843 non-null  float64
 55  rangeHwy         37843 non-null  float64
 56  rangeHwyA        37843 non-null  float64
 57  trany            37832 non-null  object
 58  UCity            37843 non-null  float64
 59  UCityA           37843 non-null  float64
 60  UHighway         37843 non-null  float64
 61  UHighwayA        37843 non-null  float64
 62  VClass           37843 non-null  object
 63  year             37843 non-null  int64
 64  youSaveSpend     37843 non-null  int64
 65  guzzler          2281 non-null   object
 66  trans_dscr       15047 non-null  object
 67  tCharger         5186 non-null   object
 68  sCharger         666 non-null    object
 69  atvType          3072 non-null   object
 70  fuelType2        1408 non-null   object
 71  rangeA           1403 non-null   object
 72  evMotor          562 non-null    object
 73  mfrCode          7025 non-null   object
 74  c240Dscr         37 non-null     object
 75  charge240b       37843 non-null  float64
 76  c240bDscr        36 non-null     object
 77  createdOn        37843 non-null  object
 78  modifiedOn       37843 non-null  object
 79  startStop        6138 non-null   object
 80  phevCity         37843 non-null  int64
 81  phevHwy          37843 non-null  int64
 82  phevComb         37843 non-null  int64
dtypes: bool(1), float64(32), int64(27), object(23)
memory usage: 23.7+ MB

# Missing Values

From this initial view, we can see that our data set contains some columns that have missing values in them and others that seem to have a lot of zero values. 

Let's see how prevalent missing values are in our data. We can use the Pandas `.isnull()` method to check whether the value in each field is missing (*null*) and return either True or False for each field. 

We can use the `.sum()` method to total up the number of True values by column, and then we can add a condition using square brackets that will filter the data and show us only columns where the number of null values were greater than zero.

## Show the number of null values only of the columns that actually have null values

In [7]:
#your code
nul_count = data.isnull().sum().sort_values(ascending=False)

nul_count

c240bDscr      37807
c240Dscr       37806
evMotor        37281
sCharger       37177
rangeA         36440
               ...
fuelCostA08        0
fuelCost08         0
feScore            0
engId              0
phevComb           0
Length: 83, dtype: int64

We can see that some columns have relatively few null values while others have tens of thousands of nulls. For fields that have a lot of null values, you will often have to make a judgement call. If you don't think the information is going to be very useful to your analysis, then you would remove those columns from your data frame.

## Remove the columns that have more than 10,000 null values in them

In Pandas, we can do that using the drop method. For our purposes, let's remove the columns that have more than 10,000 null values in them. We will add these column names to a list, and then we will pass those columns to the drop method and indicate that we want columns (not rows) dropped by setting the axis parameter to 1.

In [8]:
nulcols = [nul_count.index[i] for i in range(len(nul_count)) if nul_count[i] > 10000]

nulcols

['c240bDscr',
 'c240Dscr',
 'evMotor',
 'sCharger',
 'rangeA',
 'fuelType2',
 'guzzler',
 'atvType',
 'tCharger',
 'startStop',
 'mfrCode',
 'trans_dscr',
 'eng_dscr']

In [9]:
data.drop(columns=nulcols ,inplace=True)

In [10]:
data.isnull().sum().sort_values(ascending=False)

drive         1189
cylinders      123
displ          120
trany           11
barrels08        0
              ...
ghgScore         0
ghgScoreA        0
highway08        0
highway08U       0
phevComb         0
Length: 70, dtype: int64

This leaves us with just a handful of remaining columns that have null values. Of the columns that remain, it looks like the cylinders column and the displ column have a similar number of nulls. Perhaps they are missing for similar reasons. We can investigate this by subsetting the data set and looking at just the records where displ is null and just the columns we think will be informative in allowing us to determine a reason.

## Create a new dataframe that shows only the row where `displ` is null. 
Keep only the columns you think are useful

In [11]:
check = data[data['displ'].isnull()][['displ', 'cylinders', 'fuelType', 'fuelType1','make', 'model']]
check

,displ,cylinders,fuelType,fuelType1,make,model
7138,NaN,NaN,Electricity,Electricity,Nissan,Altra EV
7139,NaN,NaN,Electricity,Electricity,Toyota,RAV4 EV
8143,NaN,NaN,Electricity,Electricity,Toyota,RAV4 EV
8144,NaN,NaN,Electricity,Electricity,Ford,Th!nk
8146,NaN,NaN,Electricity,Electricity,Ford,Explorer USPS Electric
...,...,...,...,...,...,...
30969,NaN,NaN,Electricity,Electricity,Kia,Soul Electric
30972,NaN,NaN,Electricity,Electricity,Tesla,Model S (60 kW-hr battery pack)
30973,NaN,NaN,Electricity,Electricity,Tesla,Model S AWD - 60D
30974,NaN,NaN,Electricity,Electricity,Tesla,Model S AWD - P100D
30975,NaN,NaN,Electricity,Electricity,Tesla,Model X AWD - 60D

In [12]:
check.fuelType.value_counts()

Electricity    118
Regular          2
Name: fuelType, dtype: int64

In [13]:
check.loc[check['fuelType'].str.contains('Regular')]

       displ  cylinders fuelType         fuelType1    make     model
21413    NaN        NaN  Regular  Regular Gasoline  Subaru  RX Turbo
21414    NaN        NaN  Regular  Regular Gasoline  Subaru  RX Turbo

## Fill nan values with the most appropriate technique 
*HINT: Electric cars do not have cylinders and can therefore not have any displacement*

In [14]:
data.isnull().sum().sort_values(ascending=False)

drive         1189
cylinders      123
displ          120
trany           11
barrels08        0
              ...
ghgScore         0
ghgScoreA        0
highway08        0
highway08U       0
phevComb         0
Length: 70, dtype: int64

In [15]:
# first, we check on electric cars

test = data.copy()

condition = test['fuelType'] == 'Electricity'

test.loc[condition, ['displ', 'cylinders']] = test.loc[condition, ['displ', 'cylinders']].fillna(0)

In [16]:
test.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0

In [17]:
test.isnull().sum().sort_values(ascending=False)

drive         1189
trany           11
cylinders        3
displ            2
barrels08        0
              ...
ghgScore         0
ghgScoreA        0
highway08        0
highway08U       0
phevComb         0
Length: 70, dtype: int64

In [18]:
test[test['cylinders'].isnull()]

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
21413,13.733750,0.0,0.0,0.0,22,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,370.291667,24,0.0,0,0.0,0.0,0.0,0.0,NaN,NaN,4-Wheel Drive,0,-1,1400,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,29472,0,0,Subaru,RX Turbo,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,27.4000,0.0,38.8000,0.0,Subcompact Cars,1985,-250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
21414,14.330870,0.0,0.0,0.0,21,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,NaN,NaN,4-Wheel Drive,0,-1,1450,0,Regular,Regular Gasoline,-1,-1,27,0.0,0,0.0,0.0,0.0,0.0,0,0,29473,0,0,Subaru,RX Turbo,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,26.9000,0.0,37.1000,0.0,Subcompact Cars,1985,-500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
21506,18.311667,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,NaN,1.3,Rear-Wheel Drive,0,-1,1850,0,Regular,Regular Gasoline,-1,-1,22,0.0,0,0.0,0.0,0.0,0.0,0,0,29557,0,0,Mazda,RX-7,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,19.0473,0.0,31.1094,0.0,Two Seaters,1986,-2500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0

In [19]:
# Mazda RX-7 has a rotative motor, so we're going to adjust cylinders at 1.
# The other two we're gonna drop them because there are various models
condition = test['make'] == 'Mazda'

test.loc[condition, ['displ', 'cylinders']] = test.loc[condition, ['displ', 'cylinders']].fillna(0)

In [20]:
test.dropna(subset = ['cylinders'],inplace = True)

## Bonus: 
Now that we have filled in those null values, there are only two columns in the data set that still have null values: trany and drive. Use what you have learned in this section to investigate and potentially fill in the remaining null values.

In [40]:
test.isnull().sum().sort_values(ascending=False)

drive        1189
trany          11
barrels08       0
rangeCity       0
pv4             0
             ...
fuelType1       0
ghgScore        0
ghgScoreA       0
highway08       0
phevComb        0
Length: 70, dtype: int64

In [42]:
# electric cars are Automatic

condition = test['fuelType'] == 'Electricity'

test.loc[condition, 'trany'] = test.loc[condition,'trany'].fillna('Automatic')

In [44]:
# drop 2 values
test.dropna(subset = ['trany'],inplace = True)

In [51]:
# fill drive with unknown, if they aren't useful in the future we'll drop them

test.fillna('unknown', inplace=True)

In [53]:
# clean :)

test.isnull().sum().sort_values(ascending=False)

barrels08      0
lv4            0
pv4            0
pv2            0
phevBlended    0
              ..
fuelType       0
fuelType1      0
ghgScore       0
ghgScoreA      0
phevComb       0
Length: 70, dtype: int64

In [54]:
data = test

# Incorrect Values

In addition to null values, we also want to try to identify any values that seem incorrect. For example, in the previous section, we learned that a vehicle without cylinders should not have displacement and vice versa. Let's check to see if there are any cases that violate these rules.

In [58]:
#your code
data[(data.cylinders == 0) & (data.displ != 0)]

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
21506,18.311667,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,0.0,1.3,Rear-Wheel Drive,0,-1,1850,0,Regular,Regular Gasoline,-1,-1,22,0.0,0,0.0,0.0,0.0,0.0,0,0,29557,0,0,Mazda,RX-7,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,19.0473,0.0,31.1094,0.0,Two Seaters,1986,-2500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0

Is there any row that seems to have strange values?

In [ ]:
# That car has a 'rotative motor', which bears no cylinders but has displacement nonetheless.

Here we have identified a vehicle with a regular gasoline engine that reportedly does not have any cylinders but does have a value for displacement.

The way we would correct this would be to either perform some domain research or ask a domain expert to find out how many actual cylinders this vehicle had. Alternatively, you can also try to look at similar vehicles in the data set and determine the most likely value for this field.

## Check similar rows

In [71]:
# there are no duplicates but some of the models are the same with almost the same data

# data[data[['model']].duplicated()]

data.duplicated().any()

False

Suppose that using one of the aforementioned methods, we found out that this vehicle actually has a 4 cylinder engine. Update that specific value in the data frame.

In [69]:
#your code

## Bonus: 
 Try to find other values that might be incorrect in the data set based on what you know about automobiles and correct them.

In [26]:
#your code

# Low Variance Columns

When analyzing data, we want the fields we are working with to be informative, and we will want to strip away any columns that don't have a lot of value to us. One easy way to do this is to identify columns that have low variance, where the majority of the values in the column are the same. Since there is not a lot of variability in these columns, they have the potential to not be as informative as columns that have a variety of different values in them.

Let's try to identify columns where at least 90% of the values are the same so that we can remove them from our data set. To do this, we are going to create an empty list called low_variance that will eventually contain the names of columns that fit our criteria.

We will then write a for loop that will take the minimum and the 90th percentile value for all the numeric columns in our data set (identified via the _get_numeric_data method). If the 90th percentile and the minimum are equal to each other, that means that at least 90% of the values in that column are the same and we will append that column name to our low_variance list.

In [81]:
#your code
low_variance = []

for c in data:
    try:
        if data[c].min() == data[c].quantile(0.9):
            low_variance.append(c)
    except:
        pass

print (low_variance)

['barrelsA08', 'charge120', 'charge240', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2A', 'co2TailpipeAGpm', 'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'fuelCostA08', 'ghgScoreA', 'highwayA08', 'highwayA08U', 'highwayCD', 'highwayE', 'highwayUF', 'range', 'rangeCity', 'rangeCityA', 'rangeHwy', 'rangeHwyA', 'UCityA', 'UHighwayA', 'charge240b', 'phevCity', 'phevHwy', 'phevComb']

In [82]:
len(low_variance)

33

This returned 34 columns that we could potentially eliminate due to not having high enough variability to be informative. Of course, before we do this, we should check the values that do exist in these fields to confirm that they are not very informative. Once they have been checked, we can use the the drop method like we did earlier in this lesson to remove those columns from our data frame.

## Use the the drop method like we did earlier in this lesson to remove the non informative columns from our data frame.

In [86]:
#your code
data.drop(low_variance, axis=1, inplace=True)

# Extreme Values and Outliers

Now that we have removed low variance columns, we should look for outliers, or extreme values, in the columns that remain. These outliers can influence our aggregations when we are analyzing data later, so we want to make sure we address them during our data cleaning stage.

A common method for identifying outliers is one that leverages the interquartile range (IQR). Once the IQR is calculated, it is multiplied by a constant (typically 1.5) and lower and upper bounds are established at:

    25th Percentile - (IQR x 1.5)
    75th Percentile + (IQR x 1.5)

Any values outside this range are potential outliers and should be investigated.

Let's look at how we would do this for our data set using Python. We will use the Pandas describe function to easily calculate the 25th and 75th percentiles for every column and transpose the results so that we can easily reference the values in calculating the interquartile ranges.

In [72]:
#Run this code
stats = data.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']
stats

,count,mean,std,min,25%,50%,75%,max,IQR
barrels08,37839.0,17.532204,4.575570,0.06,14.33087,17.347895,20.600625,47.087143,6.269755
barrelsA08,37839.0,0.216192,1.141585,0.00,0.00000,0.000000,0.000000,18.311667,0.000000
charge120,37839.0,0.000000,0.000000,0.00,0.00000,0.000000,0.000000,0.000000,0.000000
charge240,37839.0,0.023533,0.427670,0.00,0.00000,0.000000,0.000000,12.000000,0.000000
city08,37839.0,17.941515,6.660517,6.00,15.00000,17.000000,20.000000,138.000000,5.000000
city08U,37839.0,4.043164,9.646241,0.00,0.00000,0.000000,0.000000,138.304000,0.000000
cityA08,37839.0,0.520204,3.838073,0.00,0.00000,0.000000,0.000000,127.000000,0.000000
cityA08U,37839.0,0.327198,3.542781,0.00,0.00000,0.000000,0.000000,127.093000,0.000000
cityCD,37839.0,0.000406,0.039920,0.00,0.00000,0.000000,0.000000,5.350000,0.000000
cityE,37839.0,0.184810,2.904711,0.00,0.00000,0.000000,0.000000,122.000000,0.000000
cityUF,37839.0,0.000706,0.019459,0.00,0.00000,0.000000,0.000000,0.849000,0.000000
co2,37839.0,61.510320,153.394476,-1.00,-1.00000,-1.000000,-1.000000,847.000000,0.000000
co2A,37839.0,5.350591,55.542394,-1.00,-1.00000,-1.000000,-1.000000,719.000000,0.000000
co2TailpipeAGpm,37839.0,17.773312,94.134081,0.00,0.00000,0.000000,0.000000,719.000000,0.000000
co2TailpipeGpm,37839.0,473.171631,122.178404,0.00,388.00000,467.736842,555.437500,1269.571429,167.437500
comb08,37839.0,20.196041,6.623504,7.00,17.00000,19.000000,23.000000,124.000000,6.000000
comb08U,37839.0,4.550232,10.390438,0.00,0.00000,0.000000,0.000000,124.360100,0.000000
combA08,37839.0,0.581252,3.966460,0.00,0.00000,0.000000,0.000000,117.000000,0.000000
combA08U,37839.0,0.359065,3.589448,0.00,0.00000,0.000000,0.000000,116.936400,0.000000
combE,37839.0,0.190595,2.979723,0.00,0.00000,0.000000,0.000000,121.000000,0.000000
combinedCD,37839.0,0.000335,0.035285,0.00,0.00000,0.000000,0.000000,4.800000,0.000000
combinedUF,37839.0,0.000691,0.019050,0.00,0.00000,0.000000,0.000000,0.834000,0.000000
cylinders,37839.0,5.719575,1.778749,0.00,4.00000,6.000000,6.000000,16.000000,2.000000
displ,37839.0,3.307746,1.371778,0.00,2.20000,3.000000,4.300000,8.400000,2.100000
engId,37839.0,8861.015619,17830.478989,0.00,0.00000,211.000000,4505.000000,69102.000000,4505.000000
feScore,37839.0,-0.035043,2.379689,-1.00,-1.00000,-1.000000,-1.000000,10.000000,0.000000
fuelCost08,37839.0,1882.039694,510.254256,550.00,1500.00000,1850.000000,2200.000000,5800.000000,700.000000
fuelCostA08,37839.0,79.078464,417.689864,0.00,0.00000,0.000000,0.000000,3800.000000,0.000000
ghgScore,37839.0,-0.037105,2.374443,-1.00,-1.00000,-1.000000,-1.000000,10.000000,0.000000
ghgScoreA,37839.0,-0.929623,0.627598,-1.00,-1.00000,-1.000000,-1.000000,8.000000,0.000000
highway08,37839.0,24.105262,6.963080,9.00,20.00000,24.000000,27.000000,111.000000,7.000000
highway08U,37839.0,5.439042,11.936827,0.00,0.00000,0.000000,0.000000,111.370000,0.000000
highwayA08,37839.0,0.686963,4.309156,0.00,0.00000,0.000000,0.000000,107.000000,0.000000
highwayA08U,37839.0,0.418742,3.809076,0.00,0.00000,0.000000,0.000000,106.531000,0.000000
highwayCD,37839.0,0.000233,0.029565,0.00,0.00000,0.000000,0.000000,4.060000,0.000000
highwayE,37839.0,0.198268,3.092024,0.00,0.00000,0.000000,0.000000,120.000000,0.000000
highwayUF,37839.0,0.000673,0.018584,0.00,0.00000,0.000000,0.000000,0.813000,0.000000
hlv,37839.0,2.026428,5.948267,0.00,0.00000,0.000000,0.000000,49.000000,0.000000
hpv,37839.0,10.425434,28.150054,0.00,0.00000,0.000000,0.000000,195.000000,0.000000
id,37839.0,19018.292502,11034.939476,1.00,9460.50000,18921.000000,28569.500000,38173.000000,19109.000000
lv2,37839.0,1.849415,4.430176,0.00,0.00000,0.000000,0.000000,41.000000,0.000000
lv4,37839.0,6.166310,9.743606,0.00,0.00000,0.000000,13.000000,55.000000,13.000000
pv2,37839.0,13.697561,31.271265,0.00,0.00000,0.000000,0.000000,194.000000,0.000000
pv4,37839.0,33.772695,45.915576,0.00,0.00000,0.000000,91.000000,192.000000,91.000000
range,37839.0,0.392717,8.251626,0.00,0.00000,0.000000,0.000000,315.000000,0.000000
rangeCity,37839.0,0.352656,8.049507,0.00,0.00000,0.000000,0.000000,305.900000,0.000000
rangeCityA,37839.0,0.036804,1.158331,0.00,0.00000,0.000000,0.000000,77.504000,0.000000
rangeHwy,37839.0,0.343436,8.172370,0.00,0.00000,0.000000,0.000000,346.900000,0.000000
rangeHwyA,37839.0,0.033479,1.032696,0.00,0.00000,0.000000,0.000000,65.632000,0.000000
UCity,37839.0,22.587415,9.350407,0.00,18.00000,21.000000,25.139300,197.577100,7.139300
UCityA,37839.0,0.652449,5.284822,0.00,0.00000,0.000000,0.000000,181.560900,0.000000
UHighway,37839.0,33.619765,10.048233,0.00,27.10000,33.000000,38.109600,159.100000,11.009600
UHighwayA,37839.0,0.933944,6.059769,0.00,0.00000,0.000000,0.000000,152.187800,0.000000
year,37839.0,2000.066043,10.389904,1984.00,1990.00000,2001.000000,2009.000000,2017.000000,19.000000
youSaveSpend,37839.0,-2658.896905,2552.967782,-22250.00,-4250.00000,-2500.000000,-750.000000,4000.000000,3500.000000
charge240b,37839.0,0.004361,0.142783,0.00,0.00000,0.000000,0.000000,7.000000,0.000000
phevCity,37839.0,0.069320,1.966910,0.00,0.00000,0.000000,0.000000,97.000000,0.000000
phevHwy,37839.0,0.068210,1.872085,0.00,0.00000,0.000000,0.000000,79.000000,0.000000
phevComb,37839.0,0.068580,1.913748,0.00,0.00000,0.000000,0.000000,88.000000,0.000000

We will then create an empty data frame called outliers with the same columns as our data set. Finally, we will loop through each column in the data calculating the lower and upper bounds, retrieving records where the value for that column falls outside the bounds we established, and appending those results to our outlier data frame.

In [30]:
#Run this code
outliers = pd.DataFrame(columns=data.columns)

for col in stats.index:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = data[(data[col] < lower) | 
                   (data[col] > upper)].copy()
    results['Outlier'] = col
    outliers = outliers.append(results)
    

outliers.head()

C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)

C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)

C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)

C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  outliers = outliers.append(results)
C:\Users\Koh\AppData\Local\Temp\ipykernel_10960\3046509943.py:12: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  outliers = outliers.append(results)

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb,Outlier
47,32.961,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,888.7,10,0.0,0,0.0,0.0,0.0,0.0,8.0,5.9,Rear-Wheel Drive,2890,-1,3350,0,Regular,Regular Gasoline,-1,-1,11,0.0,0,0.0,0.0,0.0,0.0,0,0,1004,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,11.0,0.0,15.0,0.0,Vans,1985,-10000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,barrels08
58,32.961,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,888.7,10,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2854,-1,3350,0,Regular,Regular Gasoline,-1,-1,11,0.0,0,0.0,0.0,0.0,0.0,0,0,1005,0,0,Dodge,B350 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.0,0.0,15.0,0.0,Vans,1985,-10000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,barrels08
69,32.961,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,888.7,10,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,-1,3350,0,Regular,Regular Gasoline,-1,-1,11,0.0,0,0.0,0.0,0.0,0.0,0,0,1006,0,0,Dodge,B350 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.0,0.0,15.0,0.0,Vans,1985,-10000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,barrels08
80,32.961,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,888.7,10,0.0,0,0.0,0.0,0.0,0.0,8.0,5.9,Rear-Wheel Drive,2890,-1,3350,0,Regular,Regular Gasoline,-1,-1,10,0.0,0,0.0,0.0,0.0,0.0,0,0,1007,0,0,Dodge,B350 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,11.0,0.0,14.0,0.0,Vans,1985,-10000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,barrels08
275,32.961,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,888.7,10,0.0,0,0.0,0.0,0.0,0.0,8.0,7.4,Rear-Wheel Drive,4880,-1,3350,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,10245,0,0,Chevrolet,C1500 Pickup 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 4-spd,11.0,0.0,16.0,0.0,Standard Pickup Trucks,1993,-10000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0,barrels08

Our outliers data frame should now be populated with records that you can investigate further and determine whether they should be kept in the data or dropped. The Outlier column we added before appending the results for the column to the outliers data frame will let you know what column in each record contained the outlier. If you find that this method is returning too many results, you can be more stringent with your cutoff criteria (e.g. increasing the constant by which you multiply the IQR to 3 instead of 1.5).

# Data Type Correction

One common problem that is often overlooked is incorrect data types. This typically occurs when there is a numeric variable that should actually be represented as a categorical variable.

## Check the data type of each column

In [31]:
##your code

## Cleaning years
Do you think column year is a continuous variable? Would you change it onto another dtype?

In [32]:
#your code

You can apply this technique to any column whose data type you would like to change.

In [33]:
#your code

# Cleaning Text and Removing Special Characters

The presence of special characters in our fields has the potential to make analyzing our data challenging. Imagine not being able to perform calculations on a numeric field because it was currently represented as an object data type due to the fact that it had a dollar sign ($) in it. 

Similarly, imagine having a categorical field where you could not group records that belong in the same group together because in one field you are grouping by, terms that refer to the same thing are sometimes hyphenated. In cases like this, it is necessary to remove special characters so that we can properly analyze the data.

In our vehicles data set, the trany field has several special characters (parentheses, hyphens, etc.). Check the unique values and clean the column.

hint: check the `replace` function

In [34]:
#your code

In [35]:
#your code

In [36]:
#your code

As you can see, we now have no special characters, consistent naming, and proper spacing. We started out with 47 unique values in this column, and using this technique, we were able to reduce the number of unique values to 39.



# Finding and Removing Duplicates

The final topic we are going to cover in this lab is how to identify and remove duplicate rows (or rows that refer to the same entity) in our data. When trying to identify duplicates, we will use the columns (or attributes) of the data to help us determine what entities are similar enough to be considered the same entity. We want to start with all the columns we currently have available to us and work our way toward a lesser number of attributes in an intuitive fashion. In this process, the act of dropping duplicated records is easy, but identifying the correct attributes for comparison and which records to drop is sometimes quite challenging.

The first thing we will do is attempt to drop any duplicate records, considering all the columns we currently have in the data set. 

Pandas provides us with the ability to do that via the `drop_duplicates method`.

## Drop duplicate rows that are completely equal

In [37]:
#your code

This tells us that there were no records that matched exactly across all columns. However, if we reduce the number of columns in our data that we are interested in, we can try again and have a higher likelihood of finding duplicate records.

## Select a subset of columns, remove all other columns, and then use the drop_duplicates method to drop any duplicate records based on the remaining columns.

In [38]:
#your code

#print('Number of duplicate records dropped: ', str(before - after))

With the reduced number of columns, we were able to identify and drop 885 duplicate records.

# Export clean dataset
Export your bright new clean dataset into a csv file and store it in data folder.

In [39]:
#your code