<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Data-Cleaning" data-toc-modified-id="Data-Cleaning-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data Cleaning</a></span></li><li><span><a href="#Examining-Data-for-Potential-Issues" data-toc-modified-id="Examining-Data-for-Potential-Issues-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Examining Data for Potential Issues</a></span></li><li><span><a href="#Missing-Values" data-toc-modified-id="Missing-Values-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Missing Values</a></span><ul class="toc-item"><li><span><a href="#Show-the-number-of-null-values-only-of-the-columns-that-actually-have-null-values" data-toc-modified-id="Show-the-number-of-null-values-only-of-the-columns-that-actually-have-null-values-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Show the number of null values only of the columns that actually have null values</a></span></li><li><span><a href="#Remove-the-columns-that-have-more-than-10,000-null-values-in-them" data-toc-modified-id="Remove-the-columns-that-have-more-than-10,000-null-values-in-them-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Remove the columns that have more than 10,000 null values in them</a></span></li><li><span><a href="#Create-a-new-dataframe-that-shows-only-the-row-where-displ-is-null." data-toc-modified-id="Create-a-new-dataframe-that-shows-only-the-row-where-displ-is-null.-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Create a new dataframe that shows only the row where <code>displ</code> is null.</a></span></li><li><span><a href="#Fill-nan-values-with-the-most-appropriate-technique" data-toc-modified-id="Fill-nan-values-with-the-most-appropriate-technique-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Fill nan values with the most appropriate technique</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Bonus:</a></span></li></ul></li><li><span><a href="#Incorrect-Values" data-toc-modified-id="Incorrect-Values-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Incorrect Values</a></span><ul class="toc-item"><li><span><a href="#Check-similar-rows" data-toc-modified-id="Check-similar-rows-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Check similar rows</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Bonus:</a></span></li></ul></li><li><span><a href="#Low-Variance-Columns" data-toc-modified-id="Low-Variance-Columns-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Low Variance Columns</a></span><ul class="toc-item"><li><span><a href="#Use-the-the-drop-method-like-we-did-earlier-in-this-lesson-to-remove-the-non-informative-columns-from-our-data-frame." data-toc-modified-id="Use-the-the-drop-method-like-we-did-earlier-in-this-lesson-to-remove-the-non-informative-columns-from-our-data-frame.-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Use the the drop method like we did earlier in this lesson to remove the non informative columns from our data frame.</a></span></li></ul></li><li><span><a href="#Extreme-Values-and-Outliers" data-toc-modified-id="Extreme-Values-and-Outliers-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Extreme Values and Outliers</a></span></li><li><span><a href="#Data-Type-Correction" data-toc-modified-id="Data-Type-Correction-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Data Type Correction</a></span><ul class="toc-item"><li><span><a href="#Check-the-data-type-of-each-column" data-toc-modified-id="Check-the-data-type-of-each-column-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Check the data type of each column</a></span></li><li><span><a href="#Cleaning-years" data-toc-modified-id="Cleaning-years-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Cleaning years</a></span></li></ul></li><li><span><a href="#Cleaning-Text-and-Removing-Special-Characters" data-toc-modified-id="Cleaning-Text-and-Removing-Special-Characters-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Cleaning Text and Removing Special Characters</a></span></li><li><span><a href="#Finding-and-Removing-Duplicates" data-toc-modified-id="Finding-and-Removing-Duplicates-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Finding and Removing Duplicates</a></span><ul class="toc-item"><li><span><a href="#Drop-duplicate-rows-that-are-completely-equal" data-toc-modified-id="Drop-duplicate-rows-that-are-completely-equal-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Drop duplicate rows that are completely equal</a></span></li><li><span><a href="#Select-a-subset-of-columns,-remove-all-other-columns,-and-then-use-the-drop_duplicates-method-to-drop-any-duplicate-records-based-on-the-remaining-columns." data-toc-modified-id="Select-a-subset-of-columns,-remove-all-other-columns,-and-then-use-the-drop_duplicates-method-to-drop-any-duplicate-records-based-on-the-remaining-columns.-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Select a subset of columns, remove all other columns, and then use the drop_duplicates method to drop any duplicate records based on the remaining columns.</a></span></li></ul></li><li><span><a href="#Export-clean-dataset" data-toc-modified-id="Export-clean-dataset-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Export clean dataset</a></span></li></ul></div>

# Data Cleaning


Lab Goals

+ Examine data for potential issues.
+ Identify and fill in missing values.
+ Identify and correct incorrect values.
+ Remove low variance columns.
+ Identify potential outliers.
+ Correct incorrect data types.
+ Remove special characters and clean categorical variables.
+ Identify and remove duplicate records.

Introduction

When working with data sets, you will find that they often require a bit of cleaning. Whether Pandas originally read the data types incorrectly, records are duplicated, the data contains special characters or missing value, or there are slightly different references to the same entity, every data analyst must know how to clean the data they are working with before analyzing it. In this lesson, you will learn about some of the most common problems that make data messy and methods for correcting those problems and cleaning your data.

The data set we are going to be using for this lesson is a messy version of the vehicles data set we worked with in the previous lesson. Let's import this version of our data set so that we can then practice cleaning it up.

In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_columns = False
import warnings
warnings.filterwarnings('ignore')
import re
import pylab as plt   
import seaborn as sns
%pip install matplotlib

%matplotlib inline

Requirement already satisfied: matplotlib in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (from matplotlib) (23.0)
Requirement already satisfied: pillow>=6.2.0 in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/noeliarosonmartin/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
#Load data from vehicles_messy.csv

data_original = pd.read_csv('../data/vehicles_messy.csv')
data = data_original.copy()
data.head()

   barrels08  barrelsA08  charge120  ...  phevCity  phevHwy  phevComb
0  15.695714         0.0        0.0  ...         0        0         0
1  29.964545         0.0        0.0  ...         0        0         0
2  12.207778         0.0        0.0  ...         0        0         0
3  29.964545         0.0        0.0  ...         0        0         0
4  17.347895         0.0        0.0  ...         0        0         0

[5 rows x 83 columns]

# Examining Data for Potential Issues

One of the first things we want to do is examine the data and look for any **potential issues**. Some of the things we are interested in identifying in the data at this stage include:

- Missing values
- Special characters
- Incorrect values
- Extreme values or outliers
- Duplicate records
- Incorrect data types

The presence of these may cause problems when it's time to analyze the data, so we want to make sure we address them beforehand. We can start by visually inspecting the data using the `.head` method, which will show us the first 5 rows of data.

In [3]:
#your code
data.head()

   barrels08  barrelsA08  charge120  ...  phevCity  phevHwy  phevComb
0  15.695714         0.0        0.0  ...         0        0         0
1  29.964545         0.0        0.0  ...         0        0         0
2  12.207778         0.0        0.0  ...         0        0         0
3  29.964545         0.0        0.0  ...         0        0         0
4  17.347895         0.0        0.0  ...         0        0         0

[5 rows x 83 columns]

But how big actually is our dataframe??? Check it with `.shape` method

In [4]:
#dimension original
dim_orig = data.shape
dim_orig

(37843, 83)

Let's dive a little more in the content of our data set. Is there any method that shows us the **column names**, its **data types** and number of **non-null values**?

In [5]:
#para saber informacion sobre el df
data.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 83 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   barrels08        37843 non-null  float64
 1   barrelsA08       37843 non-null  float64
 2   charge120        37843 non-null  float64
 3   charge240        37843 non-null  float64
 4   city08           37843 non-null  int64
 5   city08U          37843 non-null  float64
 6   cityA08          37843 non-null  int64
 7   cityA08U         37843 non-null  float64
 8   cityCD           37843 non-null  float64
 9   cityE            37843 non-null  float64
 10  cityUF           37843 non-null  float64
 11  co2              37843 non-null  int64
 12  co2A             37843 non-null  int64
 13  co2TailpipeAGpm  37843 non-null  float64
 14  co2TailpipeGpm   37843 non-null  float64
 15  comb08           37843 non-null  int64
 16  comb08U          37843 non-null  float64
 17  combA08          37843 non-null  int64
 18  combA08U         37843 non-null  float64
 19  combE            37843 non-null  float64
 20  combinedCD       37843 non-null  float64
 21  combinedUF       37843 non-null  float64
 22  cylinders        37720 non-null  float64
 23  displ            37723 non-null  float64
 24  drive            36654 non-null  object
 25  engId            37843 non-null  int64
 26  eng_dscr         22440 non-null  object
 27  feScore          37843 non-null  int64
 28  fuelCost08       37843 non-null  int64
 29  fuelCostA08      37843 non-null  int64
 30  fuelType         37843 non-null  object
 31  fuelType1        37843 non-null  object
 32  ghgScore         37843 non-null  int64
 33  ghgScoreA        37843 non-null  int64
 34  highway08        37843 non-null  int64
 35  highway08U       37843 non-null  float64
 36  highwayA08       37843 non-null  int64
 37  highwayA08U      37843 non-null  float64
 38  highwayCD        37843 non-null  float64
 39  highwayE         37843 non-null  float64
 40  highwayUF        37843 non-null  float64
 41  hlv              37843 non-null  int64
 42  hpv              37843 non-null  int64
 43  id               37843 non-null  int64
 44  lv2              37843 non-null  int64
 45  lv4              37843 non-null  int64
 46  make             37843 non-null  object
 47  model            37843 non-null  object
 48  mpgData          37843 non-null  object
 49  phevBlended      37843 non-null  bool
 50  pv2              37843 non-null  int64
 51  pv4              37843 non-null  int64
 52  range            37843 non-null  int64
 53  rangeCity        37843 non-null  float64
 54  rangeCityA       37843 non-null  float64
 55  rangeHwy         37843 non-null  float64
 56  rangeHwyA        37843 non-null  float64
 57  trany            37832 non-null  object
 58  UCity            37843 non-null  float64
 59  UCityA           37843 non-null  float64
 60  UHighway         37843 non-null  float64
 61  UHighwayA        37843 non-null  float64
 62  VClass           37843 non-null  object
 63  year             37843 non-null  int64
 64  youSaveSpend     37843 non-null  int64
 65  guzzler          2281 non-null   object
 66  trans_dscr       15047 non-null  object
 67  tCharger         5186 non-null   object
 68  sCharger         666 non-null    object
 69  atvType          3072 non-null   object
 70  fuelType2        1408 non-null   object
 71  rangeA           1403 non-null   object
 72  evMotor          562 non-null    object
 73  mfrCode          7025 non-null   object
 74  c240Dscr         37 non-null     object
 75  charge240b       37843 non-null  float64
 76  c240bDscr        36 non-null     object
 77  createdOn        37843 non-null  object
 78  modifiedOn       37843 non-null  object
 79  startStop        6138 non-null   object
 80  phevCity         37843 non-null  int64
 81  phevHwy          37843 non-null  int64
 82  phevComb         37843 non-null  int64
dtypes: bool(1), float64(32), int64(27), object(23)
memory usage: 59.8 MB

# Missing Values

From this initial view, we can see that our data set contains some columns that have missing values in them and others that seem to have a lot of zero values. 

Let's see how prevalent missing values are in our data. We can use the Pandas `.isnull()` method to check whether the value in each field is missing (*null*) and return either True or False for each field. 

We can use the `.sum()` method to total up the number of True values by column, and then we can add a condition using square brackets that will filter the data and show us only columns where the number of null values were greater than zero.

## Show the number of null values only of the columns that actually have null values

In [6]:
#para ver si hay nulos
data.isna()

       barrels08  barrelsA08  charge120  ...  phevCity  phevHwy  phevComb
0          False       False      False  ...     False    False     False
1          False       False      False  ...     False    False     False
2          False       False      False  ...     False    False     False
3          False       False      False  ...     False    False     False
4          False       False      False  ...     False    False     False
...          ...         ...        ...  ...       ...      ...       ...
37838      False       False      False  ...     False    False     False
37839      False       False      False  ...     False    False     False
37840      False       False      False  ...     False    False     False
37841      False       False      False  ...     False    False     False
37842      False       False      False  ...     False    False     False

[37843 rows x 83 columns]

In [7]:
col_nulas = data.isna().sum()
col_nulas[col_nulas>10000]   #para ver en que columnas hay mas de 10000 nulos

eng_dscr      15403
guzzler       35562
trans_dscr    22796
tCharger      32657
sCharger      37177
atvType       34771
fuelType2     36435
rangeA        36440
evMotor       37281
mfrCode       30818
c240Dscr      37806
c240bDscr     37807
startStop     31705
dtype: int64

We can see that some columns have relatively few null values while others have tens of thousands of nulls. For fields that have a lot of null values, you will often have to make a judgement call. If you don't think the information is going to be very useful to your analysis, then you would remove those columns from your data frame.

## Remove the columns that have more than 10,000 null values in them

In Pandas, we can do that using the drop method. For our purposes, let's remove the columns that have more than 10,000 null values in them. We will add these column names to a list, and then we will pass those columns to the drop method and indicate that we want columns (not rows) dropped by setting the axis parameter to 1.

In [8]:
#para ver en que columnas hay mas de 10000 nulos
list(col_nulas[col_nulas>1e4].index)

['eng_dscr',
 'guzzler',
 'trans_dscr',
 'tCharger',
 'sCharger',
 'atvType',
 'fuelType2',
 'rangeA',
 'evMotor',
 'mfrCode',
 'c240Dscr',
 'c240bDscr',
 'startStop']

In [9]:
#una de las formas de eliminar columnas con mas de 10000 nulos
col_borrar = col_nulas[col_nulas>1e4]
col_borrar_list = list(col_borrar.index)
col_borrar_list

['eng_dscr',
 'guzzler',
 'trans_dscr',
 'tCharger',
 'sCharger',
 'atvType',
 'fuelType2',
 'rangeA',
 'evMotor',
 'mfrCode',
 'c240Dscr',
 'c240bDscr',
 'startStop']

In [10]:
data = data.drop(col_borrar_list, axis=1)

In [11]:
data.shape #para conocer la dimension actual tras borrar las columnas

(37843, 70)

In [12]:
col_nulas = data.isna().sum()
col_nulas[col_nulas>0] #para ver el total de columnas con mas de 10000 valores nulos tras borrar

cylinders     123
displ         120
drive        1189
trany          11
dtype: int64

This leaves us with just a handful of remaining columns that have null values. Of the columns that remain, it looks like the cylinders column and the displ column have a similar number of nulls. Perhaps they are missing for similar reasons. We can investigate this by subsetting the data set and looking at just the records where displ is null and just the columns we think will be informative in allowing us to determine a reason.

## Create a new dataframe that shows only the row where `displ` is null. 
Keep only the columns you think are useful

In [13]:
#para ver los nulos en la columna displ como un df

displ_null = data[data['displ'].isnull()]
displ_null

       barrels08  barrelsA08  charge120  ...  phevCity  phevHwy  phevComb
7138       0.240         0.0        0.0  ...         0        0         0
7139       0.282         0.0        0.0  ...         0        0         0
8143       0.282         0.0        0.0  ...         0        0         0
8144       0.312         0.0        0.0  ...         0        0         0
8146       0.522         0.0        0.0  ...         0        0         0
...          ...         ...        ...  ...       ...      ...       ...
30969      0.192         0.0        0.0  ...         0        0         0
30972      0.204         0.0        0.0  ...         0        0         0
30973      0.192         0.0        0.0  ...         0        0         0
30974      0.210         0.0        0.0  ...         0        0         0
30975      0.216         0.0        0.0  ...         0        0         0

[120 rows x 70 columns]

## Fill nan values with the most appropriate technique 
*HINT: Electric cars do not have cylinders and can therefore not have any displacement*

In [14]:
data[data['drive'].isnull()]

       barrels08  barrelsA08  charge120  ...  phevCity  phevHwy  phevComb
7138    0.240000         0.0        0.0  ...         0        0         0
8144    0.312000         0.0        0.0  ...         0        0         0
8147    0.270000         0.0        0.0  ...         0        0         0
18217  15.695714         0.0        0.0  ...         0        0         0
18218  14.982273         0.0        0.0  ...         0        0         0
...          ...         ...        ...  ...       ...      ...       ...
23029   0.240000         0.0        0.0  ...         0        0         0
23030   0.546000         0.0        0.0  ...         0        0         0
23032   0.426000         0.0        0.0  ...         0        0         0
23037   0.426000         0.0        0.0  ...         0        0         0
23040   0.204000         0.0        0.0  ...         0        0         0

[1189 rows x 70 columns]

In [15]:
#suele coincidir que tanto displ y cylinders, cuando son nulos, son coches electricos, vamos a rellenar con 0


data['displ'].fillna(0.0, inplace=True)
data['cylinders'].fillna(0.0, inplace=True)

data[data['displ'].isnull()] #para comprobar que ya no hay nulos

Empty DataFrame
Columns: [barrels08, barrelsA08, charge120, charge240, city08, city08U, cityA08, cityA08U, cityCD, cityE, cityUF, co2, co2A, co2TailpipeAGpm, co2TailpipeGpm, comb08, comb08U, combA08, combA08U, combE, combinedCD, combinedUF, cylinders, displ, drive, engId, feScore, fuelCost08, fuelCostA08, fuelType, fuelType1, ghgScore, ghgScoreA, highway08, highway08U, highwayA08, highwayA08U, highwayCD, highwayE, highwayUF, hlv, hpv, id, lv2, lv4, make, model, mpgData, phevBlended, pv2, pv4, range, rangeCity, rangeCityA, rangeHwy, rangeHwyA, trany, UCity, UCityA, UHighway, UHighwayA, VClass, year, youSaveSpend, charge240b, createdOn, modifiedOn, phevCity, phevHwy, phevComb]
Index: []

In [16]:
nulas = data.isna().sum()
nulas[nulas>0]  #vemos las columnas nulas que nos quedan (drive y trany)

drive    1189
trany      11
dtype: int64

In [17]:
data['drive'].fillna('unknown', inplace=True)

In [18]:
nulas = data.isna().sum()
nulas[nulas>0]

trany    11
dtype: int64

In [19]:
data[data['trany'].isnull()]      #como es una muestra muy pequeña, vamos a eliminar esas filas

       barrels08  barrelsA08  charge120  ...  phevCity  phevHwy  phevComb
7138    0.240000         0.0        0.0  ...         0        0         0
7139    0.282000         0.0        0.0  ...         0        0         0
8143    0.282000         0.0        0.0  ...         0        0         0
8144    0.312000         0.0        0.0  ...         0        0         0
8146    0.522000         0.0        0.0  ...         0        0         0
8147    0.270000         0.0        0.0  ...         0        0         0
9212    0.258000         0.0        0.0  ...         0        0         0
9213    0.522000         0.0        0.0  ...         0        0         0
10329   0.258000         0.0        0.0  ...         0        0         0
19097  29.964545         0.0        0.0  ...         0        0         0
19128  23.543571         0.0        0.0  ...         0        0         0

[11 rows x 70 columns]

In [20]:
data.dropna(subset=['trany'], inplace=True)


nulas = data.isna().sum()
nulas[nulas>0]  #comprobamos si quedan nulos

Series([], dtype: int64)

In [21]:
#ahora vamos a comprobar si hay duplicados

data.duplicated().any()

False

In [22]:
data.describe().T

                   count          mean  ...           75%           max
barrels08        37832.0     17.536112  ...     20.600625     47.087143
barrelsA08       37832.0      0.216232  ...      0.000000     18.311667
charge120        37832.0      0.000000  ...      0.000000      0.000000
charge240        37832.0      0.023537  ...      0.000000     12.000000
city08           37832.0     17.928394  ...     20.000000    138.000000
city08U          37832.0      4.043912  ...      0.000000    138.304000
cityA08          37832.0      0.520300  ...      0.000000    127.000000
cityA08U         37832.0      0.327258  ...      0.000000    127.093000
cityCD           37832.0      0.000407  ...      0.000000      5.350000
cityE            37832.0      0.173293  ...      0.000000    122.000000
cityUF           37832.0      0.000706  ...      0.000000      0.849000
co2              37832.0     61.521648  ...     -1.000000    847.000000
co2A             37832.0      5.351766  ...     -1.000000    719.000000
co2TailpipeAGpm  37832.0     17.776600  ...      0.000000    719.000000
co2TailpipeGpm   37832.0    473.279183  ...    555.437500   1269.571429
comb08           37832.0     20.185081  ...     23.000000    124.000000
comb08U          37832.0      4.551074  ...      0.000000    124.360100
combA08          37832.0      0.581360  ...      0.000000    117.000000
combA08U         37832.0      0.359131  ...      0.000000    116.936400
combE            37832.0      0.177652  ...      0.000000    121.000000
combinedCD       37832.0      0.000335  ...      0.000000      4.800000
combinedUF       37832.0      0.000691  ...      0.000000      0.834000
cylinders        37832.0      5.720633  ...      6.000000     16.000000
displ            37832.0      3.308358  ...      4.300000      8.400000
engId            37832.0   8862.655160  ...   4505.250000  69102.000000
feScore          37832.0     -0.034865  ...     -1.000000     10.000000
fuelCost08       37832.0   1882.209505  ...   2200.000000   5800.000000
fuelCostA08      37832.0     79.093096  ...      0.000000   3800.000000
ghgScore         37832.0     -0.036926  ...     -1.000000     10.000000
ghgScoreA        37832.0     -0.929610  ...     -1.000000      8.000000
highway08        37832.0     24.096717  ...     27.000000    111.000000
highway08U       37832.0      5.440049  ...      0.000000    111.370000
highwayA08       37832.0      0.687090  ...      0.000000    107.000000
highwayA08U      37832.0      0.418820  ...      0.000000    106.531000
highwayCD        37832.0      0.000233  ...      0.000000      4.060000
highwayE         37832.0      0.183635  ...      0.000000    120.000000
highwayUF        37832.0      0.000673  ...      0.000000      0.813000
hlv              37832.0      2.026803  ...      0.000000     49.000000
hpv              37832.0     10.427363  ...      0.000000    195.000000
id               37832.0  19019.192033  ...  28573.250000  38173.000000
lv2              37832.0      1.849757  ...      0.000000     41.000000
lv4              37832.0      6.167451  ...     13.000000     55.000000
pv2              37832.0     13.700095  ...      0.000000    194.000000
pv4              37832.0     33.778944  ...     91.000000    192.000000
range            37832.0      0.377088  ...      0.000000    315.000000
rangeCity        37832.0      0.352721  ...      0.000000    305.900000
rangeCityA       37832.0      0.036810  ...      0.000000     77.504000
rangeHwy         37832.0      0.343499  ...      0.000000    346.900000
rangeHwyA        37832.0      0.033485  ...      0.000000     65.632000
UCity            37832.0     22.567952  ...     25.134150    197.577100
UCityA           37832.0      0.652570  ...      0.000000    181.560900
UHighway         37832.0     33.607389  ...     38.103300    159.100000
UHighwayA        37832.0      0.934117  ...      0.000000    152.187800
year             37832.0   2000.064971  ...   2009.000000   2017.000000
youSaveSpend     37832.0  -2659.745718  ...   -750.000000   4000.000000
charge240b       37832.0      0.004361  ...      0.000000      7.000000
phevCity         37832.0      0.069333  ...      0.000000     97.000000
phevHwy          37832.0      0.068223  ...      0.000000     79.000000
phevComb         37832.0      0.068593  ...      0.000000     88.000000

[59 rows x 8 columns]

In [23]:
data.columns

Index(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08',
       'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2',
       'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'feScore', 'fuelCost08', 'fuelCostA08',
       'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA', 'highway08',
       'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD', 'highwayE',
       'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make', 'model',
       'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'charge240b',
       'createdOn', 'modifiedOn', 'phevCity', 'phevHwy', 'phevComb'],
      dtype='object')

In [24]:
data.head()

   barrels08  barrelsA08  charge120  ...  phevCity  phevHwy  phevComb
0  15.695714         0.0        0.0  ...         0        0         0
1  29.964545         0.0        0.0  ...         0        0         0
2  12.207778         0.0        0.0  ...         0        0         0
3  29.964545         0.0        0.0  ...         0        0         0
4  17.347895         0.0        0.0  ...         0        0         0

[5 rows x 70 columns]

## Bonus: 
Now that we have filled in those null values, there are only two columns in the data set that still have null values: trany and drive. Use what you have learned in this section to investigate and potentially fill in the remaining null values.

In [25]:
#realizado en las celdas superiores

# Incorrect Values

In addition to null values, we also want to try to identify any values that seem incorrect. For example, in the previous section, we learned that a vehicle without cylinders should not have displacement and vice versa. Let's check to see if there are any cases that violate these rules.

In [26]:
#your code

Is there any row that seems to have strange values?

In [27]:
#your explanation here

Here we have identified a vehicle with a regular gasoline engine that reportedly does not have any cylinders but does have a value for displacement.

The way we would correct this would be to either perform some domain research or ask a domain expert to find out how many actual cylinders this vehicle had. Alternatively, you can also try to look at similar vehicles in the data set and determine the most likely value for this field.

## Check similar rows

In [28]:
#your code

Suppose that using one of the aforementioned methods, we found out that this vehicle actually has a 4 cylinder engine. Update that specific value in the data frame.

In [29]:
#your code

## Bonus: 
 Try to find other values that might be incorrect in the data set based on what you know about automobiles and correct them.

In [30]:
#your code

# Low Variance Columns

When analyzing data, we want the fields we are working with to be informative, and we will want to strip away any columns that don't have a lot of value to us. One easy way to do this is to identify columns that have low variance, where the majority of the values in the column are the same. Since there is not a lot of variability in these columns, they have the potential to not be as informative as columns that have a variety of different values in them.

Let's try to identify columns where at least 90% of the values are the same so that we can remove them from our data set. To do this, we are going to create an empty list called low_variance that will eventually contain the names of columns that fit our criteria.

We will then write a for loop that will take the minimum and the 90th percentile value for all the numeric columns in our data set (identified via the _get_numeric_data method). If the 90th percentile and the minimum are equal to each other, that means that at least 90% of the values in that column are the same and we will append that column name to our low_variance list.

In [31]:

low_variance = []


for col in data.select_dtypes(include=np.number):
    
    
    minimo = data[col].min()
    maximo = data[col].max()
    
    per_90 = np.percentile(data[col], 90)
    per_10 = np.percentile(data[col], 10)
    
    if minimo==per_90 or maximo==per_10:
        low_variance.append(col)
        
print(low_variance)
print(len(low_variance))

['barrelsA08', 'charge120', 'charge240', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2A', 'co2TailpipeAGpm', 'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'fuelCostA08', 'ghgScoreA', 'highwayA08', 'highwayA08U', 'highwayCD', 'highwayE', 'highwayUF', 'range', 'rangeCity', 'rangeCityA', 'rangeHwy', 'rangeHwyA', 'UCityA', 'UHighwayA', 'charge240b', 'phevCity', 'phevHwy', 'phevComb']
33

This returned 34 columns that we could potentially eliminate due to not having high enough variability to be informative. Of course, before we do this, we should check the values that do exist in these fields to confirm that they are not very informative. Once they have been checked, we can use the the drop method like we did earlier in this lesson to remove those columns from our data frame.

## Use the the drop method like we did earlier in this lesson to remove the non informative columns from our data frame.

In [32]:
data.drop(columns = low_variance, inplace = True)

# Extreme Values and Outliers

Now that we have removed low variance columns, we should look for outliers, or extreme values, in the columns that remain. These outliers can influence our aggregations when we are analyzing data later, so we want to make sure we address them during our data cleaning stage.

A common method for identifying outliers is one that leverages the interquartile range (IQR). Once the IQR is calculated, it is multiplied by a constant (typically 1.5) and lower and upper bounds are established at:

    25th Percentile - (IQR x 1.5)
    75th Percentile + (IQR x 1.5)

Any values outside this range are potential outliers and should be investigated.

Let's look at how we would do this for our data set using Python. We will use the Pandas describe function to easily calculate the 25th and 75th percentiles for every column and transpose the results so that we can easily reference the values in calculating the interquartile ranges.

In [33]:
#Run this code
stats = data.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']
stats

                  count          mean  ...           max           IQR
barrels08       37832.0     17.536112  ...     47.087143      6.269755
city08          37832.0     17.928394  ...    138.000000      5.000000
city08U         37832.0      4.043912  ...    138.304000      0.000000
co2             37832.0     61.521648  ...    847.000000      0.000000
co2TailpipeGpm  37832.0    473.279183  ...   1269.571429    167.437500
comb08          37832.0     20.185081  ...    124.000000      6.000000
comb08U         37832.0      4.551074  ...    124.360100      0.000000
cylinders       37832.0      5.720633  ...     16.000000      2.000000
displ           37832.0      3.308358  ...      8.400000      2.100000
engId           37832.0   8862.655160  ...  69102.000000   4505.250000
feScore         37832.0     -0.034865  ...     10.000000      0.000000
fuelCost08      37832.0   1882.209505  ...   5800.000000    700.000000
ghgScore        37832.0     -0.036926  ...     10.000000      0.000000
highway08       37832.0     24.096717  ...    111.000000      7.000000
highway08U      37832.0      5.440049  ...    111.370000      0.000000
hlv             37832.0      2.026803  ...     49.000000      0.000000
hpv             37832.0     10.427363  ...    195.000000      0.000000
id              37832.0  19019.192033  ...  38173.000000  19114.500000
lv2             37832.0      1.849757  ...     41.000000      0.000000
lv4             37832.0      6.167451  ...     55.000000     13.000000
pv2             37832.0     13.700095  ...    194.000000      0.000000
pv4             37832.0     33.778944  ...    192.000000     91.000000
UCity           37832.0     22.567952  ...    197.577100      7.134150
UHighway        37832.0     33.607389  ...    159.100000     11.003300
year            37832.0   2000.064971  ...   2017.000000     19.000000
youSaveSpend    37832.0  -2659.745718  ...   4000.000000   3500.000000

[26 rows x 9 columns]

We will then create an empty data frame called outliers with the same columns as our data set. Finally, we will loop through each column in the data calculating the lower and upper bounds, retrieving records where the value for that column falls outside the bounds we established, and appending those results to our outlier data frame.

In [34]:
#Run this code
outliers = pd.DataFrame(columns=data.columns)

for col in stats.index:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = data[(data[col] < lower) | 
                   (data[col] > upper)].copy()
    results['Outlier'] = col
    outliers = outliers.append(results)
    

outliers

       barrels08 city08  ...                    modifiedOn       Outlier
47     32.961000      9  ...  Tue Jan 01 00:00:00 EST 2013     barrels08
58     32.961000     10  ...  Tue Jan 01 00:00:00 EST 2013     barrels08
69     32.961000     10  ...  Tue Jan 01 00:00:00 EST 2013     barrels08
80     32.961000      9  ...  Tue Jan 01 00:00:00 EST 2013     barrels08
275    32.961000      9  ...  Tue Jan 01 00:00:00 EST 2013     barrels08
...          ...    ...  ...                           ...           ...
37475  41.201250      7  ...  Tue Jan 01 00:00:00 EST 2013  youSaveSpend
37615  27.467500     11  ...  Tue Jan 01 00:00:00 EST 2013  youSaveSpend
37672  29.964545      9  ...  Tue Jan 01 00:00:00 EST 2013  youSaveSpend
37673  29.964545      9  ...  Tue Jan 01 00:00:00 EST 2013  youSaveSpend
37827  29.964545     10  ...  Tue Jan 01 00:00:00 EST 2013  youSaveSpend

[78190 rows x 38 columns]

Our outliers data frame should now be populated with records that you can investigate further and determine whether they should be kept in the data or dropped. The Outlier column we added before appending the results for the column to the outliers data frame will let you know what column in each record contained the outlier. If you find that this method is returning too many results, you can be more stringent with your cutoff criteria (e.g. increasing the constant by which you multiply the IQR to 3 instead of 1.5).

# Data Type Correction

One common problem that is often overlooked is incorrect data types. This typically occurs when there is a numeric variable that should actually be represented as a categorical variable.

## Check the data type of each column

In [35]:
##your code
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37832 entries, 0 to 37842
Data columns (total 37 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   barrels08       37832 non-null  float64
 1   city08          37832 non-null  int64
 2   city08U         37832 non-null  float64
 3   co2             37832 non-null  int64
 4   co2TailpipeGpm  37832 non-null  float64
 5   comb08          37832 non-null  int64
 6   comb08U         37832 non-null  float64
 7   cylinders       37832 non-null  float64
 8   displ           37832 non-null  float64
 9   drive           37832 non-null  object
 10  engId           37832 non-null  int64
 11  feScore         37832 non-null  int64
 12  fuelCost08      37832 non-null  int64
 13  fuelType        37832 non-null  object
 14  fuelType1       37832 non-null  object
 15  ghgScore        37832 non-null  int64
 16  highway08       37832 non-null  int64
 17  highway08U      37832 non-null  float64
 18  hlv             37832 non-null  int64
 19  hpv             37832 non-null  int64
 20  id              37832 non-null  int64
 21  lv2             37832 non-null  int64
 22  lv4             37832 non-null  int64
 23  make            37832 non-null  object
 24  model           37832 non-null  object
 25  mpgData         37832 non-null  object
 26  phevBlended     37832 non-null  bool
 27  pv2             37832 non-null  int64
 28  pv4             37832 non-null  int64
 29  trany           37832 non-null  object
 30  UCity           37832 non-null  float64
 31  UHighway        37832 non-null  float64
 32  VClass          37832 non-null  object
 33  year            37832 non-null  int64
 34  youSaveSpend    37832 non-null  int64
 35  createdOn       37832 non-null  object
 36  modifiedOn      37832 non-null  object
dtypes: bool(1), float64(9), int64(17), object(10)
memory usage: 10.7+ MB

## Cleaning years
Do you think column year is a continuous variable? Would you change it onto another dtype?

In [36]:
# No es una variable continua, si no discreta. Por el momento, mantendremos los datos como int, aunque podrían
# modificarse a str.

data['year'].unique()

array([1985, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 1986,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 1984, 1987,
       1988, 1989, 1990, 1991, 1992, 2011, 2012, 2013, 2014, 2015, 2016,
       2017])

You can apply this technique to any column whose data type you would like to change.

In [37]:
#your code

# Cleaning Text and Removing Special Characters

The presence of special characters in our fields has the potential to make analyzing our data challenging. Imagine not being able to perform calculations on a numeric field because it was currently represented as an object data type due to the fact that it had a dollar sign ($) in it. 

Similarly, imagine having a categorical field where you could not group records that belong in the same group together because in one field you are grouping by, terms that refer to the same thing are sometimes hyphenated. In cases like this, it is necessary to remove special characters so that we can properly analyze the data.

In our vehicles data set, the trany field has several special characters (parentheses, hyphens, etc.). Check the unique values and clean the column.

hint: check the `replace` function

In [38]:
#your code
data.trany.unique()

array(['Manual 5-spd', 'Automatic 3-spd', 'Automatic 4-spd',
       'Automatic 5-spd', 'Manual 4-spd', 'Manual 3-spd', 'Manual 6-spd',
       'Automatic (S5)', 'Automatic (variable gear ratios)',
       'Automatic 6-spd', 'Automatic (S6)', 'Automatic (S4)',
       'Automatic 7-spd', 'Automatic (S7)', 'Automatic (S8)',
       'Automatic (AM5)', 'Auto(AM6)', 'Auto(AV-S7)', 'Automatic (A6)',
       'Automatic (AV-S6)', 'Auto(AM7)', 'Manual 4-spd Doubled',
       'Manual 5 spd', 'Automatic (AM6)', 'Manual 7-spd', 'Auto(L4)',
       'Auto(L3)', 'Automatic (AV)', 'Auto (AV-S6)', 'Auto(AM5)',
       'Auto(AV-S6)', 'Auto (AV-S8)', 'Automatic 8-spd', 'Auto(AV-S8)',
       'Automatic (A1)', 'Auto (AV)', 'Auto(AM-S6)', 'Auto(AM-S7)',
       'Automatic 6spd', 'Automatic 9-spd', 'Automatic (S9)',
       'Auto(AM-S8)', 'Auto(A1)', 'Auto(AM8)', 'Manual(M7)',
       'Auto(AM-S9)'], dtype=object)

In [53]:
#your code
data.trany = data.trany.apply(lambda x: re.sub(r'[^\w\s]', '', x))
data.trany.unique()

array(['Manual 5spd', 'Automatic 3spd', 'Automatic 4spd',
       'Automatic 5spd', 'Manual 4spd', 'Manual 3spd', 'Manual 6spd',
       'Automatic S5', 'Automatic variable gear ratios', 'Automatic 6spd',
       'Automatic S6', 'Automatic S4', 'Automatic 7spd', 'Automatic S7',
       'Automatic S8', 'Automatic AM5', 'AutoAM6', 'AutoAVS7',
       'Automatic A6', 'Automatic AVS6', 'AutoAM7', 'Manual 4spd Doubled',
       'Manual 5 spd', 'Automatic AM6', 'Manual 7spd', 'AutoL4', 'AutoL3',
       'Automatic AV', 'Auto AVS6', 'AutoAM5', 'AutoAVS6', 'Auto AVS8',
       'Automatic 8spd', 'AutoAVS8', 'Automatic A1', 'Auto AV',
       'AutoAMS6', 'AutoAMS7', 'Automatic 9spd', 'Automatic S9',
       'AutoAMS8', 'AutoA1', 'AutoAM8', 'ManualM7', 'AutoAMS9'],
      dtype=object)

As you can see, we now have no special characters, consistent naming, and proper spacing. We started out with 47 unique values in this column, and using this technique, we were able to reduce the number of unique values to 39.



# Finding and Removing Duplicates

The final topic we are going to cover in this lab is how to identify and remove duplicate rows (or rows that refer to the same entity) in our data. When trying to identify duplicates, we will use the columns (or attributes) of the data to help us determine what entities are similar enough to be considered the same entity. We want to start with all the columns we currently have available to us and work our way toward a lesser number of attributes in an intuitive fashion. In this process, the act of dropping duplicated records is easy, but identifying the correct attributes for comparison and which records to drop is sometimes quite challenging.

The first thing we will do is attempt to drop any duplicate records, considering all the columns we currently have in the data set. 

Pandas provides us with the ability to do that via the `drop_duplicates method`.

## Drop duplicate rows that are completely equal

In [55]:
#your code
data[data.duplicated()]

Empty DataFrame
Columns: [barrels08, city08, city08U, co2, co2TailpipeGpm, comb08, comb08U, cylinders, displ, drive, engId, feScore, fuelCost08, fuelType, fuelType1, ghgScore, highway08, highway08U, hlv, hpv, id, lv2, lv4, make, model, mpgData, phevBlended, pv2, pv4, trany, UCity, UHighway, VClass, year, youSaveSpend, createdOn, modifiedOn]
Index: []

This tells us that there were no records that matched exactly across all columns. However, if we reduce the number of columns in our data that we are interested in, we can try again and have a higher likelihood of finding duplicate records.

## Select a subset of columns, remove all other columns, and then use the drop_duplicates method to drop any duplicate records based on the remaining columns.

In [63]:
#your code
subset = ['city08U', 'comb08U', 'highway08U', 'hlv', 'hpv', 'lv2', 'lv4', 'pv2', 'pv4']
df_subset = data[subset]

subset_final = df_subset.drop_duplicates()
subset_final.duplicated().any()
#print('Number of duplicate records dropped: ', str(before - after))

False

With the reduced number of columns, we were able to identify and drop 885 duplicate records.

# Export clean dataset
Export your bright new clean dataset into a csv file and store it in data folder.

In [43]:
#your code